#!/usr/bin/env bash
#Bash script that displays numbers 1 to 100.
for x in {1..100}
do
    if (( x % 3 == 0 && x % 5 == 0 ))
    then
	echo "FizzBuzz"
    elif (( x % 5 == 0 ))
    then
	echo "Buzz"
    elif (( x % 3 == 0 ))
    then
	echo "Fizz"
    else
	echo "$x"
    fi
done

