#!/usr/bin/env bash
#Script displaying Best School 10 times but for the 9th iterations, displays Best School and then Hi on a new line.
x=0
while [ $x -le 9 ]
do
   echo "Best School"
   if [ "$a" == 8 ]
   then
       printf "%s\n" "Hi"
   fi
   ((x++))
done
